Repository nkucs/server, pull requests merged in 2019-05, with the labels that each got.

#3 DingQuan Group built the models.
  course/migrations/0001_initial.py
  course/migrations/0002_auto_20190515_2349.py
  course/models.py
  exam/migrations/0001_initial.py
  exam/migrations/0002_studentexam_problem_submissions.py
  exam/migrations/0003_auto_20190515_2349.py
  exam/models.py
  lab/migrations/0001_initial.py
  lab/migrations/0002_auto_20190515_2349.py
  lab/migrations/0003_auto_20190515_2349.py
  lab/models.py
  lecture/migrations/0001_initial.py
  lecture/migrations/0002_auto_20190515_2349.py
  lecture/models.py
  oj/settings.py
  problem/migrations/0001_initial.py
  problem/migrations/0002_auto_20190515_2349.py
  problem/models.py
  requirements.txt
  submission/migrations/0001_initial.py
  submission/migrations/0002_problemsubmission_student.py
  submission/models.py
  user/migrations/0001_initial.py
  user/models.py
Labels: good first issue

#43 hebo/get-my-labs
  lab/serializers.py
  lab/urls/admin.py
  lab/views/admin.py
  oj/urls.py
Labels: enhancement

#57 syc/add_group_model
  oj/urls.py
  user/migrations/0002_group.py
  user/models.py
Labels: enhancement

#59 syc/fix_model_name
  oj/urls.py
  user/migrations/0003_auto_20190525_1810.py
  user/models.py
Labels: bug

#64 syc/add_permission_model
  user/migrations/0004_auto_20190526_0156.py
  user/models.py
Labels: enhancement

#66 syc/add_automatic_insert_permission
  user/migrations/0005_auto_20190526_0207.py
Labels: enhancement

#71 syc/add_role_detail_api
  user/serializers.py
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#73 feat: add create role (#58)
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#74 syc/add_role_list_api
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#75 syc/add_delete_role_api
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#76 wcx/add_modify_role_api
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#77 syc/fix_role_list_api
  user/urls/admin.py
  user/views/admin.py
Labels: bug

#93 syc/fix_get_role_detail_api
  user/views/admin.py
Labels: bug

#108 feat: add field related to status of submission to submission table (#107)
  submission/models.py
Labels: enhancement

#112 fix: add migration file to server (#107)
  submission/migrations/0003_problemsubmission_submission_status.py
Labels: bug, enhancement

#113 feat: implements role teacher api set (#109)
  user/serializers.py
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#114 syc/add_mapping_permission
  user/permission.py
Labels: enhancement

#116 syc/add_confirm_permission_class
  user/permission.py
Labels: enhancement

#118 syc/fix_bug_in_permission
  user/permission.py
Labels: bug

#137 Tanglei
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#141 tanglei
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement

#143 Tanglei
  user/urls/admin.py
  user/views/admin.py
Labels: enhancement
